version: '3.9'

services:
  dbpostgres:
    image: bitnami/postgresql:latest
    container_name: finapi_db_challenge_ignite
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=fin_api
    volumes:
      - pgdata:/data/postgres

  app:
    image: node:latest
    container_name: finapi_api_challenge_ignite
    command: sh -c "yarn install && yarn dev"
    ports:
      - 3333:3333
      - 9229:9229
    working_dir: /app
    volumes:
      - ./:/app
    links:
      - dbpostgres
    depends_on:
      - dbpostgres

volumes:
  pgdata:
    driver: local
